APP_NAME = "图片处理工具"
APP_AUTHOR = "Konsheng"
APP_VERSION = "v1.0.0"
PROJECT_URL = "https://github.com/konsheng/image_tool"
PROJECT_RELEASES_URL = f"{PROJECT_URL}/releases/latest"
PROJECT_ISSUES_URL = f"{PROJECT_URL}/issues/new"

OUTPUT_SIZE_PRESETS = [
    (800, 800),
    (1000, 1000),
    (1200, 1200),
    (1440, 1440),
    (1920, 1920),
]
DEFAULT_OUTPUT_SIZE = (1440, 1440)
CUSTOM_SIZE_LABEL = "自定义"
MAX_OUTPUT_DIMENSION = 16_384
MAX_OUTPUT_PIXELS = 64_000_000

SUPPORTED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp"}

OUTPUT_FORMATS = ["JPG", "PNG", "WEBP", "保持原格式"]
DEFAULT_OUTPUT_FORMAT = "JPG"
KEEP_ORIGINAL_FORMAT = "保持原格式"

DEFAULT_MANUAL_QUALITY = 95
MIN_MANUAL_QUALITY = 1
MAX_MANUAL_QUALITY = 100

FEATURE_COMPREHENSIVE = "comprehensive"
FEATURE_RESIZE = "resize"
FEATURE_FORMAT = "format"
FEATURE_COMPRESS = "compress"
FEATURE_LOGO = "logo"
FEATURE_WATERMARK = "watermark"
FEATURE_REFERENCE_NOTICE = "reference_notice"
FEATURE_MEMO = "memo"
FEATURE_LABELS = {
    FEATURE_COMPREHENSIVE: "综合处理",
    FEATURE_RESIZE: "尺寸处理",
    FEATURE_FORMAT: "格式转换",
    FEATURE_COMPRESS: "图片压缩",
    FEATURE_LOGO: "LOGO叠加",
    FEATURE_WATERMARK: "水印",
    FEATURE_REFERENCE_NOTICE: "参考图提示",
    FEATURE_MEMO: "备忘录",
}
FEATURE_DEFAULTS = {
    FEATURE_COMPREHENSIVE: True,
    FEATURE_RESIZE: True,
    FEATURE_FORMAT: True,
    FEATURE_COMPRESS: True,
    FEATURE_LOGO: True,
    FEATURE_WATERMARK: False,
    FEATURE_REFERENCE_NOTICE: False,
    FEATURE_MEMO: True,
}
FEATURE_SETTINGS_PREFIX = "features"
COMPREHENSIVE_FEATURE_DEFAULTS = {
    FEATURE_RESIZE: True,
    FEATURE_FORMAT: True,
    FEATURE_COMPRESS: True,
    FEATURE_LOGO: True,
    FEATURE_WATERMARK: False,
    FEATURE_REFERENCE_NOTICE: False,
}
COMPREHENSIVE_FEATURE_SETTINGS_PREFIX = "comprehensive_features"

DEFAULT_REFERENCE_NOTICE_TEXT = "广告创意 图片仅供参考"
DEFAULT_REFERENCE_NOTICE_AUTO_FONT_SIZE = True
DEFAULT_REFERENCE_NOTICE_FONT_SIZE = 36
DEFAULT_REFERENCE_NOTICE_BACKGROUND_OPACITY = 65
MAX_REFERENCE_NOTICE_TEXT_LENGTH = 100
REFERENCE_NOTICE_FONT_NAME = "思源黑体 CN Medium"
REFERENCE_NOTICE_FONT_RELATIVE_PATH = "assets/fonts/SourceHanSansCN-Medium.otf"
REFERENCE_NOTICE_LICENSE_RELATIVE_PATH = "assets/fonts/LICENSE.txt"
REFERENCE_NOTICE_POSITION_TOP_LEFT = "左上"
REFERENCE_NOTICE_POSITION_TOP_RIGHT = "右上"
REFERENCE_NOTICE_POSITION_BOTTOM_LEFT = "左下"
REFERENCE_NOTICE_POSITION_BOTTOM_RIGHT = "右下"
REFERENCE_NOTICE_POSITIONS = [
    REFERENCE_NOTICE_POSITION_TOP_LEFT,
    REFERENCE_NOTICE_POSITION_TOP_RIGHT,
    REFERENCE_NOTICE_POSITION_BOTTOM_LEFT,
    REFERENCE_NOTICE_POSITION_BOTTOM_RIGHT,
]
DEFAULT_REFERENCE_NOTICE_POSITION = REFERENCE_NOTICE_POSITION_BOTTOM_RIGHT

WATERMARK_TYPE_TEXT = "文字水印"
WATERMARK_TYPE_IMAGE = "图片水印"
WATERMARK_TYPES = [WATERMARK_TYPE_TEXT, WATERMARK_TYPE_IMAGE]
WATERMARK_POSITION_CUSTOM = "自定义"
WATERMARK_POSITION_TILE = "平铺"
WATERMARK_POSITIONS = [
    "左上",
    "上中",
    "右上",
    "左中",
    "居中",
    "右中",
    "左下",
    "下中",
    "右下",
    WATERMARK_POSITION_CUSTOM,
    WATERMARK_POSITION_TILE,
]
DEFAULT_WATERMARK_TEXT = "Konsheng"
DEFAULT_WATERMARK_POSITION = "右下"
DEFAULT_WATERMARK_OPACITY = 35
DEFAULT_WATERMARK_MARGIN = 40
DEFAULT_WATERMARK_FONT_SIZE = 48
DEFAULT_WATERMARK_IMAGE_SCALE = 20
DEFAULT_WATERMARK_ANGLE = 0
DEFAULT_WATERMARK_OFFSET_X = 0
DEFAULT_WATERMARK_OFFSET_Y = 0
DEFAULT_WATERMARK_TILE_SPACING_X = 80
DEFAULT_WATERMARK_TILE_SPACING_Y = 80
DEFAULT_WATERMARK_TILE_OFFSET_X = 40
DEFAULT_WATERMARK_TILE_OFFSET_Y = 40
WATERMARK_COLORS = {
    "灰色": (102, 102, 102),
    "白色": (255, 255, 255),
    "黑色": (0, 0, 0),
    "红色": (209, 52, 56),
    "蓝色": (0, 120, 212),
}
DEFAULT_WATERMARK_COLOR = "灰色"

STATUS_PENDING = "待处理"
STATUS_PROCESSING = "处理中"
STATUS_SUCCESS = "成功"
STATUS_FAILED = "失败"
STATUS_CANCELED = "已取消"

TABLE_HEADERS = ["文件名", "格式", "尺寸", "大小", "LOGO", "状态"]


def size_to_text(size: tuple[int, int]) -> str:
    return f"{size[0]}×{size[1]} px"
